### PR TITLE
Add support for cl_khr_integer_dot_product v2

### PR DESCRIPTION
**Pull request by kpet**
Signed-off-by: Kevin Petit <kevin.petit@arm.com>

### CODE REVIEW

**Comment by kpet** [comment]
Needs testing in conjunction with https://github.com/KhronosGroup/OpenCL-Headers/pull/174 before merging.

**Review by bashbaug — APPROVED** [review]
LGTM.

I merged https://github.com/KhronosGroup/OpenCL-Headers/pull/174, so we should be able to fully test these changes now.  Would you mind rebasing and triggering a new build?  I'm not sure that I can do that, especially since the previous CI was done with the old Travis config.  Thanks!

**Comment by kpet** [comment]
@bashbaug Thanks! Now rebased and passing the new CI.

**Review by bashbaug — APPROVED** [review]
Thanks!

**Pull request merged**
