### PR TITLE
Comprehensive CMake Package Config support

### PR DESCRIPTION
**Pull request by MathiasMagnus**
This PR is part of a set of PRs implementing CMake Package Config detection support for all OpenCL repos independently and as part of the OpenCL SDK as well.

Related PRs:
- [OpenCL-Headers](https://github.com/KhronosGroup/OpenCL-Headers/pull/107)
- [OpenCL-ICD-Loader](https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/115)

I tried keeping attribution where applicable with parallel PRs were in place.

### CODE REVIEW

**Comment by sl1pkn07** [comment]
i get this when i try to build this PR

~~~
Make Error in tests/CMakeLists.txt:
  Imported target "OpenCL::OpenCL" includes non-existent path

    "/usr/include/mylib"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
~~~

**Comment by sl1pkn07** [comment]
i get this when i try to build this PR

~~~
Make Error in tests/CMakeLists.txt:
  Imported target "OpenCL::OpenCL" includes non-existent path

    "/usr/include/mylib"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
~~~

greetings

(edited again)

**Comment by sl1pkn07** [comment]
ok. problem founded

the pr https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/115  in opencl-icd-loader project creates this entry in the generated cmake files 

~~~
INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mylib"
~~~

this should be fixed for build this PR in this project

**Comment by MathiasMagnus** [comment]
Thank you @sl1pkn07 for taking it for a test drive. I'm finishing this series of PRs now (rebasing, propagating it all up to the SDK) and I'll be sure to address this. It will land sometime in the coming weeks.

**Comment by MathiasMagnus** [comment]
Superceded by #168

**Pull request closed without merging**
